### ISSUE TITLE
How to run your code on the REDDIT-BINARY

### ISSUE THREAD

**Issue by ucaswxk** [lukasjf/contrastive-gnn-explanation#1]
Hi, This is a very interesting work! The repo provides several datasets to test your model. However, I use the following order
python gnnexplainer_main.py --bmname=REDDIT-BINARY --graph-mode --explain-all
Then, I want see the result.  i cannot use the following order:
python explain.py occlusion data/REDDIT-BINARY/ ckpt/REDDIT-BINARY_base_h20_o20.pth.tar explanations/occlusion
because there is no samples. I find no ckpt about the dataset REDDIT-BINARY. 
I want to know how can I see the Figure.4 in your paper about Example Q&A explanation.
Best,
Xingkai

**Comment by lukasjf** [comment]
Hey Xingkai, thanks for your interest. We parsed this dataset differently (with a messy notebook) than the CYCLIQ one. We are currently streamlining this in the code plus testing some changes in the CoGE method.

To create the ckpt folder (which holds the model) you need to run the "gnnexplainer_train" file which trains a GNN and stores it in the cktp folder. The "gnnexplainer_main" you use would use this model to run the actual gnnexplainer method from Ying et al(https://papers.nips.cc/paper/9123-gnnexplainer-generating-explanations-for-graph-neural-networks) and create the final embeddings (that we need for our Coge) Method. Could you try to run the following command
"python gnnexplainer_train.py --bmname=REDDIT-BINARY --epochs 100" and then try the explanation again?

Also keep in mind that we created Figure 4 through CoGE but not occlusion.

**Comment by ucaswxk** [comment]
> Hey Xingkai, thanks for your interest. We parsed this dataset differently (with a messy notebook) than the CYCLIQ one. We are currently streamlining this in the code plus testing some changes in the CoGE method.
> 
> To create the ckpt folder (which holds the model) you need to run the "gnnexplainer_train" file which trains a GNN and stores it in the cktp folder. The "gnnexplainer_main" you use would use this model to run the actual gnnexplainer method from Ying et al(https://papers.nips.cc/paper/9123-gnnexplainer-generating-explanations-for-graph-neural-networks) and create the final embeddings (that we need for our Coge) Method. Could you try to run the following command
> "python gnnexplainer_train.py --bmname=REDDIT-BINARY --epochs 100" and then try the explanation again?
> 
> Also keep in mind that we created Figure 4 through CoGE but not occlusion.
hi，Lukas，I run the following command：
python gnnexplainer_train.py --bmname=REDDIT-BINARY --epochs 100" 
Then I run the  explanation  command：
python gnnexplainer_main.py --bmname=REDDIT-BINARY --graph-mode --explain-all
I get the some masked_adj_*.npy files. You said that you created Figure 4 through CoGE. So it means that if  I want to created the graph like Figure 4, I  need to analysis the masked_adj_*.npy.
Best,
Xingkai

**Comment by m30m** [comment]
Hi Xingkai,

Can you check the notebook I added in the `qualitative` folder and see if that works?

**Comment by ucaswxk** [comment]
Hi，Lukas，thanks for the contribution!
